---
driver:
  name: vagrant

provisioner:
  name: chef_solo

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: db
    run_list:
      - recipe[wfpblife2::db]
  - name: app
    run_list:
      - recipe[wfpblife2::app]
