name             'wfpblife'
maintainer       'Kevin J. Dickerson'
maintainer_email 'kevin.dickerson@loom.technology'
license          'Apache 2.0'
description      'Installs/Configures wfpblife'
long_description 'Installs/Configures wfpblife'
version          '0.1.1'

depends 'python'
depends 'newrelic'
depends 'newrelic_plugins'
depends 'apt'
depends 'php'
depends 'wordpress'
depends 'wp-cli'
depends 'database'
depends 'mysql'
depends 'varnish'
depends 'java'
